mysql-account: 2022223008
spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/${mysql-account}?createDatabaseIfNotExist=true'
    username: ${mysql-account}
    password: ${mysql-account}
    hikari:
      maximum-pool-size: 1
  sql:
    init:
      mode: always # 每次启动均执行数据库初始化脚本
  jackson:
    default-property-inclusion: non_null
  application:
    name: practice
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB

logging:
  file:
    name: D:\data\logs\mp.log
  level:
    sql: debug
    org.example.practice: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
### swagger配置
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8080


mypath: D:/data/